export const en = {
  // Welcome
  welcome_title: "Welcome to Cognitio+",
  welcome_subtitle: "Your Partner in Resilience. Rooted In Culture. Powered by Awareness. Enhanced by Technology.",
  mission_statement: "Our Mission: Empowering Local Communities to Seamlessly Integrate Mental Health and Substance Abuse Services into Primary Healthcare.",
  get_started: "Get Started",

  // User Type
  who_are_you: "Who are you?",
  choose_one_to_personalize: "Choose one to personalize your experience.",
  user_type_individual_title: "I’m Here for Myself",
  user_type_individual_desc: "Improve my well-being or get support",
  user_type_mhp_title: "I’m a Mental Health Professional",
  user_type_mhp_desc: "Provide therapy, counseling, or care",
  user_type_community_title: "I Represent a Community",
  user_type_community_desc: "Work with LGUs, schools, or groups",
  user_type_organization_title: "I Represent an Organization",
  user_type_organization_desc: "From a company, NGO, or institution",

  // Buttons
  next: "Next",
  back: "Back",
  finish: "Finish",
  start_over: "Start Over",
  close: "Close",
  done: "Done",
  measure_again: "Measure Again",

  // Header
  header_progress: "Badge Progress",
  header_logout: "Logout",
  header_dashboard: "Dashboard",
  header_subscription: "Subscription",
  header_upgrade: "Upgrade",
  header_habits: "Habits",
  header_growth_tribe: "GROWTH Tribe",

  // Dashboard
  dashboard_welcome: "Your personalized space is ready.",
  badge_unlocked: "Badge Unlocked:",
  recommendations_title: "Recommended For You",
  no_recommendations: "No specific recommendations at this time. Explore our services to learn more!",
  onboarding_summary: "Onboarding Summary",
  
  // Individual Dashboard
  hrv_checkin_title: "HRV Check-in",
  hrv_checkin_desc: "Measure your Heart Rate Variability to track your nervous system's resilience.",
  hrv_checkin_cta: "Measure Now",
  hrv_chart_title: "Your HRV Stress Level",
  hrv_chart_desc: "This reflects your nervous system's current state. Higher HRV often means better stress resilience.",
  hrv_status_low: "Low Stress",
  hrv_status_balanced: "Balanced",
  hrv_status_high: "High Stress",
  hrv_last_score: "Last HRV:",
  ai_insight_title: "Today's Insight",
  gamification_title: "Engagement Status",
  gamification_desc: "check-ins away from your next badge!",
  booking_title: "Access Support",
  booking_desc: "Your personalized recommendations are ready. Take the next step.",
  booking_cta: "Book a Session",
  booking_cta_short: "Book Now",
  subsidy_cta: "Request Subsidy",
  breathing_exercise_cta: "Try a Breathing Exercise",
  
  // Breathing Modal
  breathing_title: "Guided Breathing",
  breathing_desc: "Follow the animation to regulate your nervous system. Find a comfortable position and begin.",
  breathe_in: "Breathe In...",
  breathe_hold: "Hold...",
  breathe_out: "Breathe Out...",

  // HRV Measurement Modal
  hrv_measurement_title: "HRV Measurement",
  hrv_measurement_desc: "Follow the guide to breathe calmly for 60 seconds for an accurate reading.",
  hrv_measurement_instruction: "🌿 Find a quiet space • 🤫 Stay still and relax",
  hrv_measurement_start: "Start Measurement",
  hrv_measurement_result_title: "Your HRV Result",
  hrv_measurement_result_desc_good: "Good recovery — your nervous system is balanced.",
  hrv_measurement_result_desc_moderate: "Moderate stress — try more breathing exercises.",
  hrv_measurement_result_desc_high: "High stress — rest and recheck tomorrow.",
  hrv_trend_title: "Your 5-Day Trend",
  hrv_trend_desc: "Comparing your latest HRV score with your recent measurements.",
  mindfulness_cta: "Start 3-Min Mindfulness",
  mindfulness_title: "Guided Mindfulness",
  mindfulness_desc: "Continue to breathe with the flower. Let your thoughts come and go without judgment.",
  mindfulness_complete_title: "Session Complete",
  mindfulness_complete_desc: "You've taken a moment for yourself. Carry this calmness with you.",

  // Habit Designer
  habit_designer_title: "Resilient Habit Designer",
  habit_designer_dashboard_cta: "Build habits that stick, based on science and your own insights.",
  habit_designer_ai_cta: "Design a Resilience Habit",
  habit_menu_title: "Resilient Habit Designer",
  habit_menu_subtitle: "Build habits that stick — using science, simplicity, and self-awareness.",
  habit_menu_guide_title: "7-Step Guide",
  habit_menu_guide_desc: "Follow the proven framework",
  habit_menu_guide_step_1: "Start with Celebration",
  habit_menu_guide_step_2: "Map Your Motivation",
  habit_menu_guide_step_3: "Simplify the Behavior",
  habit_menu_guide_step_4: "Design Your Prompt",
  habit_menu_guide_step_5: "Test & Iterate",
  habit_menu_guide_step_6: "Scale Gradually",
  habit_menu_guide_step_7: "Anchor to Daily Life",
  habit_menu_guide_cta: "Start Designing",
  habit_menu_videos_title: "Learn with Videos",
  habit_menu_videos_desc: "Watch mini-lessons",
  habit_menu_video_1: "How to Find Your Motivation",
  habit_menu_video_2: "Make It Easier Than Easy",
  habit_menu_video_3: "The Power of Tiny Prompts",
  habit_menu_ai_title: "AI Suggestion",
  habit_menu_ai_desc: "Based on your HRV data",
  habit_menu_ai_suggestion: "You’ve shown high stress in the evenings. Try designing a <strong>5-minute breathing habit</strong> after dinner.",
  habit_menu_ai_cta: "Try This Habit",
  habit_menu_my_habits_title: "Your Habits",
  habit_menu_my_habits_desc: "Track your progress",
  habit_menu_my_habits_empty: "No habits created yet.",
  habit_menu_my_habits_cta: "Create First Habit",
  habit_designer_step_celebration_title: "Step 1: Celebrate a Strength",
  habit_designer_step_celebration_placeholder: "What are you already doing well, even if it's small? (e.g., 'I drink a glass of water when I wake up.') Celebrate it!",
  habit_designer_step_motivation_title: "Step 2: What's Your Motivation?",
  habit_designer_step_motivation_placeholder: "What deeper feeling or outcome are you hoping for? (e.g., 'To feel less anxious in the mornings,' 'To have more energy for my kids.')",
  habit_designer_step_behavior_title: "Step 3: Make it Tiny",
  habit_designer_step_behavior_placeholder: "What's a tiny, easy version of your desired habit? (e.g., 'Do 1 push-up,' not 'Work out for 1 hour.' 'Breathe deeply 3 times,' not 'Meditate for 20 minutes.')",
  habit_designer_step_prompt_title: "Step 4: Find a Prompt",
  habit_designer_step_prompt_placeholder: "When and where will you do this tiny habit? Anchor it to something you already do. (e.g., 'After I brush my teeth, I will...' 'When my head hits the pillow, I will...')",
  habit_designer_finish_cta: "Finish & Save",

  // GROWTH Tribe Forum
  forum_title: "GROWTH Tribe Forum",
  forum_subtitle: "Share. Support. Grow. Every caring interaction builds resilience.",
  forum_placeholder: "How are you doing today? What’s one small win or challenge?",
  forum_anonymous_post: "Post anonymously",
  forum_share_button: "Share Your Story",
  forum_loading: "Loading community stories...",
  forum_no_posts: "No posts yet. Be the first to share!",
  forum_reply_placeholder: "Offer support or encouragement...",
  forum_reply_button: "Reply",
  badge_supportive_peer_name: "Supportive Peer",
  badge_supportive_peer_desc: "You've started supporting your community. Thank you!",


  // Community Dashboard
  community_dashboard_circles_title: "Manage CareTalk Circles",
  community_dashboard_circles_desc: "Organize and facilitate peer support groups within your community.",
  community_dashboard_circles_cta: "Create a Circle",
  community_dashboard_training_title: "Access Training Modules",
  community_dashboard_training_desc: "Equip community leaders with Psychological First Aid (PFA) skills.",
  community_dashboard_training_cta: "View Trainings",

  // Organization Dashboard
  org_dashboard_trends_title: "Team Well-being Trends",
  org_dashboard_trends_desc: "Monitor aggregated, anonymous data on your team's stress and resilience levels.",
  org_dashboard_trends_placeholder: "Well-being data chart will be displayed here.",

  // Subscription Page
  subscription_title: "Unlock Your Full Potential",
  subscription_desc: "Choose a plan that fits your journey. Upgrade to access premium features and deeper insights.",
  current_plan: "Current Plan",
  upgrade_cta: "Upgrade to Premium",
  individual_plan_name: "Cognitio+ Premium",
  individual_plan_price: "₱299 / month",
  individual_plan_feature_1: "Advanced AI-Powered Insights",
  individual_plan_feature_2: "Historical HRV & Mood Tracking",
  individual_plan_feature_3: "Unlimited Journaling",
  individual_plan_feature_4: "Priority Support",
  mhp_plan_name: "MHP Pro",
  mhp_plan_price: "₱999 / month",
  mhp_plan_feature_1: "Secure Client Notes & Management",
  mhp_plan_feature_2: "Advanced Scheduling Tools",
  mhp_plan_feature_3: "Priority Referrals",
  mhp_plan_feature_4: "Access to Professional-Only Content",
  processing_payment: "Processing Your Subscription...",
  payment_success: "Welcome to Premium!",
  return_to_dashboard: "Return to Dashboard",
  
  // Premium Features & Locks
  feature_locked: "Premium Feature Locked",
  unlock_now: "Upgrade your plan to unlock this feature and gain deeper insights into your well-being.",
  premium_feature: "Premium",
  premium_ai_insight: "Unlock deeper, personalized AI insights by upgrading to Premium.",
  premium_hrv_history: "View Your 7-Day HRV Trend",


  // Individual Onboarding
  individual_goal_title: "What brings you here?",
  individual_goal_stress: "Reduce stress",
  individual_goal_sleep: "Improve sleep",
  individual_goal_emotions: "Understand my emotions",
  individual_goal_burnout: "Recover from burnout",
  individual_goal_talk: "Find someone to talk to",
  individual_context_title: "Which describes your current situation? (Select all that apply)",
  individual_context_student: "Student managing school stress",
  individual_context_remote: "Living in a remote area",
  individual_context_indigenous: "Part of an Indigenous community",
  individual_context_disability: "Have a disability",
  individual_context_financial: "Managing financial stress",
  individual_context_none: "None of the above",
  individual_counseling_title: "How would you prefer to connect with a professional?",
  individual_counseling_video: "Online video sessions",
  individual_counseling_chat: "Chat-based counseling",
  individual_counseling_person: "In-person sessions",
  individual_counseling_unsure: "I'm not sure yet",
  individual_checkin_title: "Let's do a quick check-in. How are you feeling right now?",
  individual_checkin_5: "Feeling Great (5/5)",
  individual_checkin_4: "Feeling Good (4/5)",
  individual_checkin_3: "Feeling Okay (3/5)",
  individual_checkin_2: "Struggling a bit (2/5)",
  individual_checkin_1: "Feeling Overwhelmed (1/5)",

  // MHP Onboarding
  mhp_role_title: "What is your primary professional role?",
  mhp_role_psychologist: "Psychologist",
  mhp_role_psychiatrist: "Psychiatrist",
  mhp_role_counselor: "Guidance Counselor",
  mhp_role_social_worker: "Social Worker",
  mhp_role_pwd_specialist: "PWD Specialist",
  mhp_identity_title: "Professional Identity",
  mhp_services_title: "Which services or specializations do you offer? (Select all that apply)",
  mhp_service_cbt: "Cognitive Behavioral Therapy (CBT)",
  mhp_service_dbt: "Dialectical Behavior Therapy (DBT)",
  mhp_service_trauma: "Trauma-Informed Care",
  mhp_service_addiction: "Addiction & Substance Abuse Counseling",
  mhp_service_family: "Family & Couples Therapy",
  mhp_service_psychiatric: "Psychiatric Consultation & Medication Management",
  mhp_community_title: "Would you like to serve underserved communities?",
  mhp_community_yes: "Yes, I would",
  mhp_community_no: "Not at this time",

  // Community Onboarding
  community_type_title: "What type of community do you represent?",
  community_type_lgu: "Barangay (LGU)",
  community_type_school: "School",
  community_type_indigenous: "Indigenous Group",
  community_type_cso: "Civil Society Organization (CSO)",
  community_profile_title: "Community Profile",
  community_needs_title: "What are the most pressing mental health needs in your community? (Select all that apply)",
  community_needs_youth: "Youth mental health support (e.g., anxiety, depression)",
  community_needs_substance: "Substance abuse prevention and support",
  community_needs_carers: "Support for teachers and front-liners (burnout)",
  community_needs_disaster: "Post-disaster psychosocial support",
  community_needs_resilience: "General emotional resilience building",
  community_funding_title: "Do you have a mental health budget or funder?",
  community_funding_yes: "Yes, we have a budget/funder",
  community_funding_no: "No, we are seeking support",

  // Organization Onboarding
  org_profile_title: "Organization Profile",
  org_goals_title: "What are your organization's mental health goals?",
  org_goals_burnout: "Reduce employee burnout",
  org_goals_train_managers: "Train managers in mental health support",
  org_goals_emergency: "Integrate MHPSS into emergency plans",
  org_goals_policy: "Develop and implement a mental health policy",
  org_goals_wellbeing: "Improve overall team well-being",
  org_compliance_title: "How would you describe your organization's status regarding the DOH Mental Health Act (RA 11036)?",
  org_compliance_full: "Fully Compliant",
  org_compliance_partial: "Partially Compliant, working towards full compliance",
  org_compliance_non: "Not yet compliant, seeking guidance",
  org_compliance_unsure: "Unsure about the requirements",
};
