export const tl = {
  // Welcome
  welcome_title: "Maligayang pagdating sa Cognitio+",
  welcome_subtitle: "Ang Iyong Kasama sa Katatagan. Nakaugat sa Kultura. Pinapatakbo ng Kamalayan. Pinahusay ng Teknolohiya.",
  mission_statement: "Aming Misyon: Bigyang-kapangyarihan ang mga Lokal na Komunidad upang Walang Sagabal na Isama ang mga Serbisyo sa Kalusugang Pangkaisipan at Pag-abuso sa Sustansya sa Pangunahing Pangangalagang Pangkalusugan.",
  get_started: "Magsimula",

  // User Type
  who_are_you: "Sino ka?",
  choose_one_to_personalize: "Pumili ng isa para i-personalize ang iyong karanasan.",
  user_type_individual_title: "Nandito Ako para sa Sarili Ko",
  user_type_individual_desc: "Pabutihin ang aking kapakanan o kumuha ng suporta",
  user_type_mhp_title: "Ako ay isang Mental Health Professional",
  user_type_mhp_desc: "Nagbibigay ng therapy, counseling, o pangangalaga",
  user_type_community_title: "Kinakatawan Ko ang isang Komunidad",
  user_type_community_desc: "Nakikipagtulungan sa mga LGU, paaralan, o grupo",
  user_type_organization_title: "Kinakatawan Ko ang isang Organisasyon",
  user_type_organization_desc: "Mula sa isang kumpanya, NGO, o institusyon",

  // Buttons
  next: "Susunod",
  back: "Bumalik",
  finish: "Tapusin",
  start_over: "Magsimulang Muli",
  close: "Isara",
  done: "Tapos na",
  measure_again: "Sukating Muli",

  // Header
  header_progress: "Progreso ng Badge",
  header_logout: "Mag-logout",
  header_dashboard: "Dashboard",
  header_subscription: "Subskripsyon",
  header_upgrade: "Mag-upgrade",
  header_habits: "Mga Gawi",
  header_growth_tribe: "GROWTH Tribe",

  // Dashboard
  dashboard_welcome: "Handa na ang iyong personalized na espasyo.",
  badge_unlocked: "Nakuha ang Badge:",
  recommendations_title: "Inirerekomenda Para Sa Iyo",
  no_recommendations: "Walang mga tiyak na rekomendasyon sa ngayon. Galugarin ang aming mga serbisyo para matuto pa!",
  onboarding_summary: "Buod ng Onboarding",
  
  // Individual Dashboard
  hrv_checkin_title: "HRV Check-in",
  hrv_checkin_desc: "Sukatin ang iyong Heart Rate Variability para masubaybayan ang katatagan ng iyong nervous system.",
  hrv_checkin_cta: "Sukatin Ngayon",
  hrv_chart_title: "Ang Iyong Antas ng Stress sa HRV",
  hrv_chart_desc: "Ito ay sumasalamin sa kasalukuyang estado ng iyong nervous system. Ang mas mataas na HRV ay madalas nangangahulugang mas mahusay na katatagan sa stress.",
  hrv_status_low: "Mababang Stress",
  hrv_status_balanced: "Balanse",
  hrv_status_high: "Mataas na Stress",
  hrv_last_score: "Huling HRV:",
  ai_insight_title: "Kaalaman Ngayong Araw",
  gamification_title: "Katayuan ng Pakikilahok",
  gamification_desc: "na check-in na lang para sa susunod mong badge!",
  booking_title: "Mag-access ng Suporta",
  booking_desc: "Handa na ang iyong mga personal na rekomendasyon. Gawin ang susunod na hakbang.",
  booking_cta: "Mag-book ng Session",
  booking_cta_short: "Mag-book Na",
  subsidy_cta: "Humiling ng Tulong Pinansyal",
  breathing_exercise_cta: "Subukan ang Ehersisyo sa Paghinga",
  
  // Breathing Modal
  breathing_title: "Giniyahang Paghinga",
  breathing_desc: "Sundan ang animation para makontrol ang iyong nervous system. Humanap ng komportableng posisyon at magsimula.",
  breathe_in: "Huminga paloob...",
  breathe_hold: "Pigilan...",
  breathe_out: "Huminga palabas...",

  // HRV Measurement Modal
  hrv_measurement_title: "Pagsukat ng HRV",
  hrv_measurement_desc: "Sundan ang gabay para sa mahinahong paghinga sa loob ng 60 segundo para sa tumpak na resulta.",
  hrv_measurement_instruction: "🌿 Humanap ng tahimik na lugar • 🤫 Manatiling kalmado at huwag gumalaw",
  hrv_measurement_start: "Simulan ang Pagsukat",
  hrv_measurement_result_title: "Resulta ng Iyong HRV",
  hrv_measurement_result_desc_good: "Magandang recovery — balanse ang iyong nervous system.",
  hrv_measurement_result_desc_moderate: "Katamtamang stress — subukan ang mas maraming ehersisyo sa paghinga.",
  hrv_measurement_result_desc_high: "Mataas na stress — magpahinga at suriing muli bukas.",
  hrv_trend_title: "Ang Iyong 5-Araw na Trend",
  hrv_trend_desc: "Paghahambing ng iyong pinakabagong iskor sa HRV sa iyong mga kamakailang sukat.",
  mindfulness_cta: "Simulan ang 3-Minutong Mindfulness",
  mindfulness_title: "Giniyahang Mindfulness",
  mindfulness_desc: "Ipagpatuloy ang paghinga kasama ng bulaklak. Hayaan lang ang iyong mga iniisip na dumaan nang walang paghuhusga.",
  mindfulness_complete_title: "Kumpleto na ang Session",
  mindfulness_complete_desc: "Naglaan ka ng sandali para sa iyong sarili. Dalhin ang kapayapaang ito sa iyo.",

  // Habit Designer
  habit_designer_title: "Disenyo ng Matatag na Gawi",
  habit_designer_dashboard_cta: "Bumuo ng mga gawi na tumatagal, batay sa agham at sa iyong sariling mga kaalaman.",
  habit_designer_ai_cta: "Magdisenyo ng Gawi para sa Katatagan",
  habit_menu_title: "Disenyo ng Matatag na Gawi",
  habit_menu_subtitle: "Bumuo ng mga gawi na tumatagal — gamit ang agham, pagiging simple, at kamalayan sa sarili.",
  habit_menu_guide_title: "Gabay na may 7 Hakbang",
  habit_menu_guide_desc: "Sundin ang subok na balangkas",
  habit_menu_guide_step_1: "Magsimula sa Pagdiriwang",
  habit_menu_guide_step_2: "Tukuyin ang Iyong Motibasyon",
  habit_menu_guide_step_3: "Pasimplehin ang Gawi",
  habit_menu_guide_step_4: "Idisenyo ang Iyong Paalala",
  habit_menu_guide_step_5: "Subukan at Ulitin",
  habit_menu_guide_step_6: "Palakihin nang Dahan-dahan",
  habit_menu_guide_step_7: "I-angkla sa Pang-araw-araw na Buhay",
  habit_menu_guide_cta: "Simulan ang Pagdisenyo",
  habit_menu_videos_title: "Matuto sa mga Video",
  habit_menu_videos_desc: "Manood ng maiikling aralin",
  habit_menu_video_1: "Paano Hanapin ang Iyong Motibasyon",
  habit_menu_video_2: "Gawing Mas Madali Kaysa sa Madali",
  habit_menu_video_3: "Ang Kapangyarihan ng Maliliit na Paalala",
  habit_menu_ai_title: "Mungkahi ng AI",
  habit_menu_ai_desc: "Batay sa iyong data ng HRV",
  habit_menu_ai_suggestion: "Nagpakita ka ng mataas na stress sa gabi. Subukang magdisenyo ng isang <strong>5-minutong gawi sa paghinga</strong> pagkatapos ng hapunan.",
  habit_menu_ai_cta: "Subukan ang Gawi na Ito",
  habit_menu_my_habits_title: "Ang Iyong mga Gawi",
  habit_menu_my_habits_desc: "Subaybayan ang iyong pag-unlad",
  habit_menu_my_habits_empty: "Wala pang mga gawi na nalikha.",
  habit_menu_my_habits_cta: "Lumikha ng Unang Gawi",
  habit_designer_step_celebration_title: "Hakbang 1: Ipagdiwang ang isang Kalakasan",
  habit_designer_step_celebration_placeholder: "Ano ang nagagawa mo nang maayos, kahit na maliit? (hal., 'Umiinom ako ng isang basong tubig pagkagising.') Ipagdiwang ito!",
  habit_designer_step_motivation_title: "Hakbang 2: Ano ang Iyong Motibasyon?",
  habit_designer_step_motivation_placeholder: "Anong mas malalim na damdamin o resulta ang iyong inaasahan? (hal., 'Para mabawasan ang pagkabalisa sa umaga,' 'Para magkaroon ng mas maraming enerhiya para sa aking mga anak.')",
  habit_designer_step_behavior_title: "Hakbang 3: Gawing Napakaliit",
  habit_designer_step_behavior_placeholder: "Ano ang isang napakaliit at madaling bersyon ng iyong nais na gawi? (hal., 'Gumawa ng 1 push-up,' hindi 'Mag-ehersisyo ng 1 oras.' 'Huminga nang malalim ng 3 beses,' hindi 'Mag-meditate ng 20 minuto.')",
  habit_designer_step_prompt_title: "Hakbang 4: Humanap ng Paalala",
  habit_designer_step_prompt_placeholder: "Kailan at saan mo gagawin ang maliit na gawi na ito? I-angkla ito sa isang bagay na ginagawa mo na. (hal., 'Pagkatapos kong magsipilyo, gagawin ko...' 'Kapag ang ulo ko ay tumama sa unan, gagawin ko...')",
  habit_designer_finish_cta: "Tapusin at I-save",

  // GROWTH Tribe Forum
  forum_title: "GROWTH Tribe Forum",
  forum_subtitle: "Magbahagi. Sumuporta. Lumago. Bawat mapagkalingang interaksyon ay nagpapatibay ng katatagan.",
  forum_placeholder: "Kumusta ka ngayon? Ano ang isang maliit na tagumpay o hamon?",
  forum_anonymous_post: "Mag-post nang hindi nagpapakilala",
  forum_share_button: "Ibahagi ang Iyong Kwento",
  forum_loading: "Nilo-load ang mga kwento ng komunidad...",
  forum_no_posts: "Wala pang mga post. Maging una sa pagbabahagi!",
  forum_reply_placeholder: "Mag-alok ng suporta o pampalakas-loob...",
  forum_reply_button: "Tumugon",
  badge_supportive_peer_name: "Matulunging Kapwa",
  badge_supportive_peer_desc: "Nagsimula ka nang sumuporta sa iyong komunidad. Salamat!",

  // Community Dashboard
  community_dashboard_circles_title: "Pamahalaan ang CareTalk Circles",
  community_dashboard_circles_desc: "Ayusin at pangasiwaan ang mga peer support group sa loob ng iyong komunidad.",
  community_dashboard_circles_cta: "Gumawa ng Circle",
  community_dashboard_training_title: "I-access ang mga Modyul sa Pagsasanay",
  community_dashboard_training_desc: "Bigyan ang mga lider ng komunidad ng mga kasanayan sa Psychological First Aid (PFA).",
  community_dashboard_training_cta: "Tingnan ang mga Pagsasanay",

  // Organization Dashboard
  org_dashboard_trends_title: "Mga Trend sa Kapakanan ng Koponan",
  org_dashboard_trends_desc: "Subaybayan ang pinagsama-samang, hindi nakikilalang data sa mga antas ng stress at katatagan ng iyong koponan.",
  org_dashboard_trends_placeholder: "Ang tsart ng data ng kapakanan ay ipapakita dito.",

  // Subscription Page
  subscription_title: "I-unlock ang Iyong Buong Potensyal",
  subscription_desc: "Pumili ng plano na akma sa iyong paglalakbay. Mag-upgrade para ma-access ang mga premium na feature at mas malalim na kaalaman.",
  current_plan: "Kasalukuyang Plano",
  upgrade_cta: "Mag-upgrade sa Premium",
  individual_plan_name: "Cognitio+ Premium",
  individual_plan_price: "₱299 / buwan",
  individual_plan_feature_1: "Mga Advanced na AI-Powered Insight",
  individual_plan_feature_2: "Makasaysayang Pagsubaybay sa HRV at Mood",
  individual_plan_feature_3: "Walang limitasyong Journaling",
  individual_plan_feature_4: "Priority na Suporta",
  mhp_plan_name: "MHP Pro",
  mhp_plan_price: "₱999 / buwan",
  mhp_plan_feature_1: "Ligtas na Tala ng Kliyente at Pamamahala",
  mhp_plan_feature_2: "Mga Advanced na Tool sa Pag-iiskedyul",
  mhp_plan_feature_3: "Mga Priority na Referral",
  mhp_plan_feature_4: "Access sa Nilalaman para sa mga Propesyonal Lamang",
  processing_payment: "Pinoproseso ang Iyong Subskripsyon...",
  payment_success: "Maligayang pagdating sa Premium!",
  return_to_dashboard: "Bumalik sa Dashboard",
  
  // Premium Features & Locks
  feature_locked: "Naka-lock ang Premium na Feature",
  unlock_now: "I-upgrade ang iyong plano para i-unlock ang feature na ito at magkaroon ng mas malalim na pag-unawa sa iyong kapakanan.",
  premium_feature: "Premium",
  premium_ai_insight: "I-unlock ang mas malalim, personal na mga AI insight sa pamamagitan ng pag-upgrade sa Premium.",
  premium_hrv_history: "Tingnan ang Iyong 7-Araw na Trend ng HRV",

  // Individual Onboarding
  individual_goal_title: "Anong nagdala sa iyo dito?",
  individual_goal_stress: "Bawasan ang stress",
  individual_goal_sleep: "Pabutihin ang tulog",
  individual_goal_emotions: "Unawain ang aking mga damdamin",
  individual_goal_burnout: "Maka-recover sa burnout",
  individual_goal_talk: "Maghanap ng makakausap",
  individual_context_title: "Alin ang naglalarawan sa iyong kasalukuyang sitwasyon? (Piliin lahat ng angkop)",
  individual_context_student: "Estudyanteng namamahala sa stress sa paaralan",
  individual_context_remote: "Nakatira sa isang malayong lugar",
  individual_context_indigenous: "Bahagi ng isang Katutubong komunidad",
  individual_context_disability: "May kapansanan",
  individual_context_financial: "Namamahala sa problemang pinansyal",
  individual_context_none: "Wala sa nabanggit",
  individual_counseling_title: "Paano mo gustong kumonekta sa isang propesyonal?",
  individual_counseling_video: "Mga online video session",
  individual_counseling_chat: "Counseling na nakabase sa chat",
  individual_counseling_person: "Mga personal na session",
  individual_counseling_unsure: "Hindi pa ako sigurado",
  individual_checkin_title: "Mag-check-in tayo. Kumusta ang pakiramdam mo ngayon?",
  individual_checkin_5: "Napakabuti ng pakiramdam (5/5)",
  individual_checkin_4: "Mabuti ang pakiramdam (4/5)",
  individual_checkin_3: "Okay lang (3/5)",
  individual_checkin_2: "Medyo nahihirapan (2/5)",
  individual_checkin_1: "Sobrang bigat ng nararamdaman (1/5)",

  // MHP Onboarding
  mhp_role_title: "Ano ang iyong pangunahing propesyonal na tungkulin?",
  mhp_role_psychologist: "Psychologist",
  mhp_role_psychiatrist: "Psychiatrist",
  mhp_role_counselor: "Guidance Counselor",
  mhp_role_social_worker: "Social Worker",
  mhp_role_pwd_specialist: "PWD Specialist",
  mhp_identity_title: "Propesyonal na Pagkakakilanlan",
  mhp_services_title: "Anong mga serbisyo o espesyalisasyon ang iyong inaalok? (Piliin lahat ng angkop)",
  mhp_service_cbt: "Cognitive Behavioral Therapy (CBT)",
  mhp_service_dbt: "Dialectical Behavior Therapy (DBT)",
  mhp_service_trauma: "Pangangalaga na may Kaalaman sa Trauma",
  mhp_service_addiction: "Paggabay sa Adiksyon at Pag-abuso sa Sustansya",
  mhp_service_family: "Therapy para sa Pamilya at Mag-asawa",
  mhp_service_psychiatric: "Konsultasyong Saykayatriko at Pamamahala ng Gamot",
  mhp_community_title: "Gusto mo bang maglingkod sa mga komunidad na kulang sa serbisyo?",
  mhp_community_yes: "Oo, gusto ko",
  mhp_community_no: "Hindi sa ngayon",

  // Community Onboarding
  community_type_title: "Anong uri ng komunidad ang iyong kinakatawan?",
  community_type_lgu: "Barangay (LGU)",
  community_type_school: "Paaralan",
  community_type_indigenous: "Katutubong Grupo",
  community_type_cso: "Civil Society Organization (CSO)",
  community_profile_title: "Profile ng Komunidad",
  community_needs_title: "Ano ang mga pinakamahalagang pangangailangan sa kalusugang pangkaisipan sa iyong komunidad? (Piliin lahat ng angkop)",
  community_needs_youth: "Suporta para sa kalusugang pangkaisipan ng kabataan (hal., pagkabalisa, depresyon)",
  community_needs_substance: "Pag-iwas at suporta sa pag-abuso sa droga",
  community_needs_carers: "Suporta para sa mga guro at front-liner (burnout)",
  community_needs_disaster: "Sikolohikal na suporta pagkatapos ng sakuna",
  community_needs_resilience: "Pangkalahatang pagbuo ng katatagan ng emosyon",
  community_funding_title: "Mayroon ka bang badyet o pondo para sa kalusugang pangkaisipan?",
  community_funding_yes: "Oo, mayroon kaming badyet/pondo",
  community_funding_no: "Wala, kami ay naghahanap ng suporta",

  // Organization Onboarding
  org_profile_title: "Profile ng Organisasyon",
  org_goals_title: "Ano ang mga layunin ng iyong organisasyon para sa kalusugang pangkaisipan?",
  org_goals_burnout: "Bawasan ang burnout ng mga empleyado",
  org_goals_train_managers: "Sanayin ang mga manager sa suporta sa kalusugang pangkaisipan",
  org_goals_emergency: "Isama ang MHPSS sa mga plano para sa emergency",
  org_goals_policy: "Bumuo at magpatupad ng patakaran sa kalusugang pangkaisipan",
  org_goals_wellbeing: "Pabutihin ang pangkalahatang kapakanan ng team",
  org_compliance_title: "Paano mo ilalarawan ang status ng iyong organisasyon tungkol sa DOH Mental Health Act (RA 11036)?",
  org_compliance_full: "Ganap na Sumusunod",
  org_compliance_partial: "Bahagyang Sumusunod, nagsusumikap para sa ganap na pagsunod",
  org_compliance_non: "Hindi pa sumusunod, naghahanap ng gabay",
  org_compliance_unsure: "Hindi sigurado sa mga kinakailangan",
};
